//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzemeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malzemeler()
        {
            this.SatisUrunler = new HashSet<SatisUrunler>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Kod { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
        public Nullable<int> Grup { get; set; }
        public Nullable<int> Marka { get; set; }
        public Nullable<int> GelisFiyat { get; set; }
        public Nullable<int> GelisAdet { get; set; }
    
        public virtual MalzemeGrubu MalzemeGrubu { get; set; }
        public virtual MalzemeMarkaları MalzemeMarkaları { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisUrunler> SatisUrunler { get; set; }
    }
}
