//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakip.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class İsTakipEntities : DbContext
    {
        public İsTakipEntities()
            : base("name=İsTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Departmanlar> Departmanlar { get; set; }
        public virtual DbSet<Firmalar> Firmalar { get; set; }
        public virtual DbSet<GorevDetaylar> GorevDetaylar { get; set; }
        public virtual DbSet<Gorevler> Gorevler { get; set; }
        public virtual DbSet<MalzemeGrubu> MalzemeGrubu { get; set; }
        public virtual DbSet<Malzemeler> Malzemeler { get; set; }
        public virtual DbSet<MalzemeMarkaları> MalzemeMarkaları { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Cagrilar> Cagrilar { get; set; }
        public virtual DbSet<CagriDetay> CagriDetay { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<SatisUrunler> SatisUrunler { get; set; }
    }
}
